APP-1404: wizard bug fix
heybaton/formio-ng pull request #4
Opened 2022-09-29 14:24 UTC by rendee-heybaton

closes https://github.com/heybaton/app/issues/1404

note: reverted to version 5.2.2

2022-10-03 10:35 UTC, ecvelayo requested changes
fix conflicts

2022-10-04 07:54 UTC, rvalledorjr approved these changes

2022-10-06 15:14 UTC, brycen-ong approved these changes

2022-10-07 14:31 UTC, paint-it-green approved these changes

2022-10-07 14:46 UTC, ecvelayo approved these changes

2022-10-10 23:25 UTC, merged